[pytest]
testpaths =
    unit_tests
    API_tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q
filterwarnings =
    ignore:datetime\.datetime\.utcnow\(\) is deprecated and scheduled for removal in a future version\.:DeprecationWarning:jose\.jwt
